AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Cloudformation template'

Resources:
  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties: 
      UserName: 'FJ89CFN'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'